name: Get permission for mod
description: Track permission to create patches for a mod
title: Get permission for <title>
body:
 - type: "dropdown"
   id: gameDomainName
   attributes:
    label: "Nexus Mods game domain name"
    options: ["starfield"]
   validations:
    required: true
 - type: "input"
   id: modPlatformId
   attributes:
    label: "Nexus Mods mod ID"
   validations:
    required: true
 - type: "input"
   id: modCode
   attributes:
    label: "Mod code"
   validations:
    required: true
 - type: markdown
   attributes:
    value: |
     The [mod page for <modPlatformId>-<modCode>](https://www.nexusmods.com/<gameDomainName>/mods/<modPlatformId>) states the following:

     > **Modification permission**
     > You must get permission from me before you are allowed to modify my files to improve it

     We should get explicit permission to make compatibility patches.
